/**
 * Story UI — Storybook manager addon.
 *
 * Three jobs:
 *
 * 1. The Story UI PAGE. The workspace is hosted here, in Storybook's manager,
 *    at `?path=/workspace/`, rather than in the docs page inside the preview
 *    iframe. Storybook re-renders that docs page from scratch whenever a story
 *    enters its index — which every generation does — so the live narration,
 *    step list and in-flight stream were torn down mid-run. The manager never
 *    remounts on index changes. Registered as `types.experimental_PAGE`, the
 *    same API Storybook's own Settings page uses (a `types.TAB` is deprecated
 *    in 10.x, needs a story to be selected, and lives inside the canvas
 *    toolbar). The page itself comes from the package
 *    (`@tpitre/story-ui/manager`), loaded on first visit so the manager's
 *    startup path stays small; the MDX docs entry remains as the fallback for
 *    Storybook 8, where this file is not wired.
 *
 * 2. A "Story UI" toolbar button on every story, and an "Edit in Story UI"
 *    one on stories generated by Story UI (title under the "Generated/"
 *    prefix). The latter stashes the story's component id in sessionStorage
 *    (shared same-origin with the page) and opens the page, which picks up
 *    the stash and opens that story's conversation.
 *
 * 3. Focus mode for the docs-page workspace (the fallback surface). While
 *    that docs entry is the active story, Storybook's sidebar and addons
 *    panel are folded away and restored exactly as they were on the way out.
 *    The workspace's "Focus" button toggles it by postMessage; the preference
 *    is `story-ui-focus` in localStorage. On the page, the same preference
 *    folds the sidebar; that lives in the page module.
 *
 * Wired up from .storybook/manager.ts(x):
 *   import '../src/stories/StoryUI/manager';
 *
 * Requires Storybook 9+ (the consolidated `storybook/manager-api` package).
 */
import React from 'react';
import { addons, types, useStorybookApi, useStorybookState } from 'storybook/manager-api';
import { Route } from 'storybook/internal/router';
import '@tpitre/story-ui/manager.css';

const EDIT_REQUEST_KEY = 'story-ui-edit-request';
/**
 * The page's route. Not `/story-ui/`: Storybook shows the canvas for any path
 * matching `^\/story`, which would paint the (empty) preview over the page.
 * Defined here, where the page is registered; the package's manager module
 * does not import it (a static import there would evaluate the whole
 * workspace bundle at manager startup — see LazyStoryUIPage below).
 */
const STORY_UI_ROUTE = '/workspace/';
/**
 * sessionStorage flag set when the page is registered. The preview iframe
 * shares sessionStorage with the manager (same origin, same tab), so the MDX
 * fallback page (StoryUIV2.mdx reads the same key) can tell that a better
 * surface exists and point at it. Session-scoped on purpose: an un-wired
 * addon must not leave a stale promise behind.
 */
const TAB_FLAG_KEY = 'story-ui-tab';
/**
 * The `<Meta title>` in StoryUIV2.mdx — the docs fallback. Its id is looked
 * up from Storybook's index by this title so the docs-page focus flow keeps
 * working for anyone who opens that entry directly.
 */
const WORKSPACE_TITLE = 'Story UI/Workspace';
const WORKSPACE_DOCS_ID = 'story-ui-workspace--docs';
const PANEL_DOCS_ID = 'story-ui-story-generator--docs';
const GENERATED_PREFIX = 'Generated/';

/** localStorage key for the focus preference; "false" is the only opt-out. */
const FOCUS_KEY = 'story-ui-focus';
/** postMessage types, preview → manager and manager → preview. */
const FOCUS_MESSAGE = 'story-ui:focus';
const FOCUS_STATE_MESSAGE = 'story-ui:focus-state';
/**
 * What the chrome was before Story UI folded it — sessionStorage, shared with
 * the page module, rather than a ref. A full reload while folded loses every
 * ref, and the hidden sidebar then looked like the user's own choice. Whoever
 * mounts next (this tool on a story, the page on its route) restores it.
 */
const CHROME_BEFORE_FOCUS_KEY = 'story-ui-chrome-before-focus';
interface SavedChrome { nav: boolean; panel?: boolean }
const readSavedChrome = (): SavedChrome | null => {
  try {
    const raw = sessionStorage.getItem(CHROME_BEFORE_FOCUS_KEY);
    const parsed = raw ? JSON.parse(raw) : null;
    return parsed && typeof parsed.nav === 'boolean' ? parsed : null;
  } catch { return null; }
};
const writeSavedChrome = (value: SavedChrome | null) => {
  try {
    if (value) sessionStorage.setItem(CHROME_BEFORE_FOCUS_KEY, JSON.stringify(value));
    else sessionStorage.removeItem(CHROME_BEFORE_FOCUS_KEY);
  } catch { /* private mode */ }
};

/**
 * The page module, fetched on first visit. `import()` of a package module
 * is inlined by Storybook's IIFE manager build, so this is about deferring
 * evaluation (Radix Themes and the workspace) until the page is opened, not
 * about a separate chunk. A failure to load is shown in place rather than
 * taking the manager down.
 */
const LazyStoryUIPage = React.lazy(() =>
  // @ts-ignore — resolved from the installed package when the PROJECT's Storybook builds this file
  import('@tpitre/story-ui/manager').then((m: any) => ({ default: m.StoryUIPage as React.FC })),
);

class PageBoundary extends React.Component<{ children: React.ReactNode }, { error: Error | null }> {
  state = { error: null as Error | null };
  static getDerivedStateFromError(error: Error) { return { error }; }
  render() {
    if (this.state.error) {
      return (
        <div style={{ padding: 24, font: '13px/1.5 system-ui, sans-serif' }}>
          <strong>Story UI could not load.</strong>
          <pre style={{ whiteSpace: 'pre-wrap', opacity: 0.8 }}>{String(this.state.error?.message ?? this.state.error)}</pre>
          <p>Is <code>@tpitre/story-ui</code> installed? The docs entry "Story UI / Workspace" still works as a fallback.</p>
        </div>
      );
    }
    return this.props.children;
  }
}

const Loading: React.FC = () => (
  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', font: '13px system-ui, sans-serif', opacity: 0.7 }}>
    Loading Story UI…
  </div>
);

/** The page slot, filled only while the route matches so nothing runs in the background. */
const StoryUIPageRoute: React.FC = () => (
  <Route path={STORY_UI_ROUTE} startsWith>
    <div style={{ display: 'flex', flexDirection: 'column', flex: '1 1 auto', minHeight: 0, height: '100%' }}>
      <PageBoundary>
        <React.Suspense fallback={<Loading />}>
          <LazyStoryUIPage />
        </React.Suspense>
      </PageBoundary>
    </div>
  </Route>
);

/** `navigateUrl` takes the URL as written, which a non-story `?path=` needs. */
const openStoryUi = (api: ReturnType<typeof useStorybookApi>) => {
  try {
    api.navigateUrl(`?path=${STORY_UI_ROUTE}`, {});
  } catch {
    window.location.search = `?path=${STORY_UI_ROUTE}`;
  }
};

interface StoryUiTargets {
  /** The workspace docs entry's real id, when the project has one. */
  workspaceId: string | null;
}

/**
 * Whether this project still has the docs-page workspace, for the focus
 * flow below. Read from Storybook's own /index.json: same-origin,
 * version-proof, and the check every other part of Story UI already uses.
 */
function useStoryUiTarget(): StoryUiTargets {
  const [targets, setTargets] = React.useState<StoryUiTargets>({ workspaceId: null });
  React.useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('index.json');
        if (!res.ok) return;
        const entries: Record<string, any> = (await res.json())?.entries ?? {};
        const byTitle = Object.values(entries).find(
          (e: any) => e?.type === 'docs' && e?.title === WORKSPACE_TITLE,
        ) as { id?: string } | undefined;
        const workspaceId = byTitle?.id ?? (entries[WORKSPACE_DOCS_ID] ? WORKSPACE_DOCS_ID : null);
        if (!cancelled) setTargets({ workspaceId });
      } catch {
        /* no docs fallback — the page is the only surface, which is fine */
      }
    })();
    return () => { cancelled = true; };
  }, []);
  return targets;
}

const readFocusPreference = (): boolean => {
  try { return localStorage.getItem(FOCUS_KEY) !== 'false'; } catch { return true; }
};

const writeFocusPreference = (on: boolean) => {
  try { localStorage.setItem(FOCUS_KEY, on ? 'true' : 'false'); } catch { /* private mode */ }
};

/** Tell the docs-page workspace what the chrome is actually doing, so its button agrees. */
const postFocusState = (on: boolean) => {
  try {
    const frame = document.getElementById('storybook-preview-iframe') as HTMLIFrameElement | null;
    frame?.contentWindow?.postMessage({ type: FOCUS_STATE_MESSAGE, on }, window.location.origin);
  } catch { /* no preview frame yet */ }
};

/**
 * Fold Storybook's sidebar and addons panel away while the DOCS-PAGE
 * workspace is the active story, and restore them on the way out. The page
 * has its own, simpler version of this (only the sidebar exists there).
 *
 * `toggleNav(false)` / `togglePanel(false)`, not `setOptions({ showNav })`:
 * in Storybook 10 the layout state no longer has `showNav`/`showPanel` at
 * all — visibility IS `navSize > 0` and the panel's size > 0 — so setOptions
 * with those keys is a silent no-op, while the toggles are the real setters
 * (and persist per session only, so nothing leaks into the user's saved
 * layout). `getIsNavShown` / `getIsPanelShown` read the same truth, which is
 * what makes the restore exact rather than "show everything".
 */
function useWorkspaceFocus(api: ReturnType<typeof useStorybookApi>, storyId: string, workspaceId: string | null) {
  const [wanted, setWanted] = React.useState<boolean>(readFocusPreference);

  // The workspace's Focus button, from inside the preview frame. Messages
  // from this document itself belong to the page module, not here.
  React.useEffect(() => {
    const onMessage = (e: MessageEvent) => {
      if (e.origin !== window.location.origin || e.source === window) return;
      const msg = e.data;
      if (!msg || msg.type !== FOCUS_MESSAGE || typeof msg.on !== 'boolean') return;
      writeFocusPreference(msg.on);
      setWanted(msg.on);
    };
    window.addEventListener('message', onMessage);
    return () => window.removeEventListener('message', onMessage);
  }, []);

  const onWorkspace = !!workspaceId && storyId === workspaceId;
  const focus = onWorkspace && wanted;

  const restore = React.useCallback(() => {
    const saved = readSavedChrome();
    if (!saved || typeof api?.toggleNav !== 'function') return;
    api.toggleNav(saved.nav);
    if (typeof saved.panel === 'boolean' && typeof api.togglePanel === 'function') api.togglePanel(saved.panel);
    writeSavedChrome(null);
  }, [api]);

  React.useEffect(() => {
    const canToggle = typeof api?.toggleNav === 'function' && typeof api?.togglePanel === 'function';
    if (!canToggle) return;
    if (focus) {
      if (!readSavedChrome()) {
        writeSavedChrome({
          nav: typeof api.getIsNavShown === 'function' ? api.getIsNavShown() : true,
          panel: typeof api.getIsPanelShown === 'function' ? api.getIsPanelShown() : true,
        });
      }
      api.toggleNav(false);
      api.togglePanel(false);
      postFocusState(true);
      return;
    }
    if (onWorkspace) {
      // Focus turned off while still on the workspace is a request to SEE
      // the sidebar, whatever it was before; the exact restore is for leaving.
      if (readSavedChrome()) {
        api.toggleNav(true);
        writeSavedChrome(null);
      }
      postFocusState(false);
      return;
    }
    // Also heals a fold left behind by a reload of the page or the docs
    // workspace: the saved state outlives the component that wrote it.
    restore();
  }, [api, focus, onWorkspace, restore]);

  // Leaving the manager entirely (the tool unmounts) must not strand the user
  // without a sidebar.
  React.useEffect(() => () => restore(), [restore]);
}

const toolButtonStyle: React.CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
  height: 28,
  padding: '0 10px',
  margin: '2px 0',
  border: 0,
  borderRadius: 4,
  background: 'transparent',
  color: 'inherit',
  font: 'inherit',
  fontSize: 12,
  fontWeight: 700,
  cursor: 'pointer',
};

const hover = {
  onMouseEnter: (e: React.MouseEvent<HTMLButtonElement>) => { e.currentTarget.style.background = 'rgba(2, 156, 253, 0.12)'; },
  onMouseLeave: (e: React.MouseEvent<HTMLButtonElement>) => { e.currentTarget.style.background = 'transparent'; },
};

const EditIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <path d="M12 20h9" />
    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
  </svg>
);

const SparkIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1" />
    <circle cx="12" cy="12" r="3" />
  </svg>
);

const StoryUITools: React.FC = () => {
  const api = useStorybookApi();
  // Subscribing to manager state re-renders the tool on story navigation.
  useStorybookState();
  const { workspaceId } = useStoryUiTarget();

  const current = api.getCurrentStoryData?.();
  const title: string = (current as any)?.title ?? '';
  const storyId: string = (current as any)?.id ?? '';

  useWorkspaceFocus(api, storyId, workspaceId);

  // Story UI's own entries get no button to themselves.
  if (!storyId || storyId === workspaceId || storyId === WORKSPACE_DOCS_ID || storyId === PANEL_DOCS_ID) {
    return null;
  }

  const generated = title.startsWith(GENERATED_PREFIX);

  const openEditor = () => {
    if (generated) {
      try {
        sessionStorage.setItem(
          EDIT_REQUEST_KEY,
          JSON.stringify({ componentId: storyId.split('--')[0], title })
        );
      } catch {
        /* sessionStorage unavailable — the page just opens without preselection */
      }
    }
    openStoryUi(api);
  };

  return (
    <button
      onClick={openEditor}
      title={generated ? "Open this story's chat in Story UI" : 'Open Story UI'}
      style={toolButtonStyle}
      {...hover}
    >
      {generated ? <EditIcon /> : <SparkIcon />}
      {generated ? 'Edit in Story UI' : 'Story UI'}
    </button>
  );
};

addons.register('story-ui', () => {
  try { sessionStorage.setItem(TAB_FLAG_KEY, STORY_UI_ROUTE); } catch { /* private mode */ }

  addons.add('story-ui/workspace', {
    type: types.experimental_PAGE,
    url: STORY_UI_ROUTE,
    title: 'Story UI',
    render: StoryUIPageRoute,
  });

  addons.add('story-ui/edit-tool', {
    type: types.TOOL,
    title: 'Story UI',
    match: ({ viewMode }) => viewMode === 'story' || viewMode === 'docs',
    render: () => <StoryUITools />,
  });
});
